name: 'üåû CI'

on:
  workflow_dispatch:  
  pull_request:
    paths-ignore:
      - '**.md'
      - dist/**
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - dist/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: maxisam/action-inspector@main

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref}}

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - run: yarn install

      - run: yarn all

      - name: Compare the expected and actual dist/ directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            echo "::set-output name=diff::true"
          fi

      - name: commit build
        if: ${{ steps.diff.outputs.diff }}
        run: |
          git config --local user.email "maxisam@gmail.com"
          git config --local user.name "maxisam"
          git add dist/
          git commit -m "chore: build, dist updated"
          git push origin ${{ github.ref_name }}
          
  action:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: "CI Check Report"
          conclusion: ${{ needs.build.result }}
          # check-run is tied to a commit, so for PR, it need to use head.sha
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          summary: "Check Summary"
          content: |
            ## Check Report Example
            - ‚òÄÔ∏è everything works
          detailsUrl: "https://github.com/maxisam/check-report"

  test-workflow:
    uses: maxisam/check-report/.github/workflows/.workflow-a.yml@main
    with:
      sha: ${{ github.event.pull_request.head.sha || github.sha }}